# Overrides for local dev environment

version: '3'
services:
  realtime:
    command: mix test
    environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    build: ./dev/postgres
    ports:
      - "5432:5432"