# docker-compose.yml

version: '3'
services:
  realtime:
    build: ./
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      APP_PORT: 4000
      APP_HOSTNAME: localhost
      SECRET_KEY_BASE: SOMETHING_SUPER_SECRET
  
  