# docker-compose.yml

version: '3'
services:
  realtime:
      build: ./server
      environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
  db:
    build: ./test/postgres
    ports:
      - "6543:5432"
  