# use this user for running the service
- name: System user
  user: name=realtime

- name: Install hex dependecy
  shell: mix local.hex --force
  become_user: realtime
  args:
    chdir: /opt/realtime/server

- name: Install rebar dependency
  shell: mix local.rebar --force
  become_user: realtime
  args:
    chdir: /opt/realtime/server

- name: Install other dependencies
  shell: mix deps.get
  become_user: realtime
  args:
    chdir: /opt/realtime/server

- name: Build release
  # IF A BUILD EXISTS the following message is shown
  # Release realtime-0.7.1 already exists. Overwrite? [Yn]
  #
  # There is no flag to stop if an existing build is available, thus we pipe 'n' to stop
  shell: echo n | MIX_ENV=prod mix release
  become_user: realtime
  args:
    chdir: /opt/realtime/server

- name: Create /etc/realtime.env
  copy:
    src: files/realtime.env
    dest: /etc/realtime.env
    owner: realtime

- name: Create service file
  template:
    src: files/realtime.service.j2
    dest: /etc/systemd/system/realtime.service

- name: Enable service
  systemd:
    daemon_reload: yes
    name: realtime
    enabled: yes

- name: Restart service
  service: name=realtime state=restarted
