---
- name: System user
  user: name=realtime

# We use bsdtar instead of unzip, because we want to remove the first path component.
# E.g. when downloading a branch archive that first directory will be realtime-BRANCHNAME
# but when specifying a commit id the directory will be realtime-COMMITID
# bsdtar supports this feature, see http://archive.vn/M7DL8
- name: System dependencies
  apt:
    pkg:
      - bsdtar

- name: Download commit archive
  get_url:
    url: "https://github.com/supabase/realtime/archive/{{ supabase_commit }}.zip"
    dest: /tmp/realtime.zip
    checksum: "{{ supabase_commit_checksum }}"

- name: Create /opt/realtime
  file:
    path: /opt/realtime
    state: directory
    owner: realtime

- name: Unpack archive to /opt/realtime
  shell: bsdtar --strip-components=1 -xvf /tmp/realtime.zip
  become_user: realtime
  args:
    chdir: /opt/realtime

# Supabase server is build using Elixir and it uses the Elixir mix build tool
# See http://archive.vn/EqPby
- name: Download erlang-solutions deb
  get_url:
    url: "https://packages.erlang-solutions.com/{{ erlang_solutions_deb }}"
    dest: /tmp/erlang-solutions.deb
    checksum: "{{ erlang_solutions_deb_checksum }}"

- name: Install erlang-solutions deb
  apt: deb=file:///tmp/erlang-solutions.deb

- name: Install esl-erlang and elixir
  apt:
    update_cache: yes
    pkg:
      - esl-erlang
      - elixir
