name: CI
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mix-format:
    name: Mix-Format and Credo tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp: [24.x]
        elixir: [1.13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Cache Mix
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get
      - name: Run format check
        run: mix format --check-formatted
      - name: Credo checks
        run: mix credo --strict --mute-exit-status
      - name: Retrieve PLT Cache
        uses: actions/cache@v1
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
      # - name: Run dialyzer
      #   run: mix dialyzer --no-check --halt-exit-status
